### ISSUE TITLE
"Find Jobs" Button overlapping for Tab view

### ISSUE THREAD

**Issue by Chinmay2660** [TechieeGeeeks/JobSet#34]

**Comment by Chinmay2660** [comment]
<img width="567" alt="Screenshot 2023-07-14 at 4 25 33 PM" src="https://github.com/TechieeGeeeks/JobSet/assets/74097022/5a8827a5-9dd3-4225-88d4-9497f9b83980">

Find jobs button is getting overlapped for Tab view

**Comment by DevSwayam** [comment]
You can start working on it

**Comment by siam1113** [comment]
@Chinmay2660 
Can you add a screenshot pointing to the problem ?
