### ISSUE TITLE
Contact us page enhancement. 

### ISSUE THREAD

**Issue by DevSwayam** [TechieeGeeeks/JobSet#42]
### Why? 
So I added contact us page by literally copy pasting from tailwind css components. 
### What is needed ?
So the components is not configured according to use case.
On the submit the whole message should get sent to owners mail id. You can do it via email.js. 
### support
If you need any kind of help feel free to open discussion on it. 

## Important Note
Pro's could you all stay away from good first issues it's ment for beginners so that they won't have hard time contributing on repo. You'll literally killing good first issues in 10-15 mins I hope you'll understand ❤️.

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by DevSwayam** [comment]
> Can I get assigned? let me know how to start.

You can start eorking on it.

**Comment by anyanime** [comment]
> Can I get assigned? let me know how to start.

Please @Pulkitxm are you currently working on this issue?

**Comment by DevSwayam** [comment]
> > Can I get assigned? let me know how to start.
> 
> Please @Pulkitxm are you currently working on this issue?

It's done

**Comment by anyanime** [comment]
Okay.
