### ISSUE TITLE
Website Title and Title icon

### ISSUE THREAD

**Issue by DevSwayam** [TechieeGeeeks/JobSet#47]
### Task
Can Anyone add Website a Title "JobSet " with a icon 
![image](https://github.com/TechieeGeeeks/JobSet/assets/99035115/b7838fa6-350b-42cb-bbed-26a8fb712c49)
Like This

**Comment by LOGESH-B** [comment]
Hii @DevSwayam 
I created PR at #48 😁

**Comment by DevSwayam** [comment]
> Hii @DevSwayam I created PR at #48 😁 ![image](https://user-images.githubusercontent.com/86541143/253804298-593f029a-0e25-4170-b0af-988a10ca894c.png)

Good work 👍

**Comment by DevSwayam** [comment]
@LOGESH-B bro push the static svh file and again make a PR.

**Comment by LOGESH-B** [comment]
@DevSwayam 
sry I copied the link of the logo from nav.
Now i moved the logo to public dir
I raised a PR at #50 
![image](https://github.com/TechieeGeeeks/JobSet/assets/86541143/f3630bef-5932-4f73-aa2c-8317d8447966)

**Comment by DevSwayam** [comment]
Done by @LOGESH-B Good work.
