### ISSUE TITLE
Changes required in Footer section

### ISSUE THREAD

**Issue by Abhi270303** [TechieeGeeeks/JobSet#54]
![WhatsApp Image 2023-07-16 at 7 58 33 PM](https://github.com/TechieeGeeeks/JobSet/assets/87358315/2ce493f8-fc83-4245-8d89-122146c33a4d)
<h1>1) Add Twitter and LinkedIn Icons in right corner
<h1>2) Change to the correct Copyright format

**Comment by kotkaravishkar** [comment]
Can I work on it ?

**Comment by BisiOlaYemi** [comment]
@kotkaravishkar The task is already set to done. It is completed and merged

**Comment by DevSwayam** [comment]
Thank You
