### ISSUE TITLE
Small Bug For Beginners

### ISSUE THREAD

**Issue by DevSwayam** [TechieeGeeeks/JobSet#73]
So on the Resources page. Their is small bug their is color difference between the components. 
![image](https://github.com/TechieeGeeeks/JobSet/assets/99035115/6bf9e33e-d6bf-4996-bb55-04f31fc9f793)
You just have to change a small css property. and make it white like whole website.

**Comment by JesusC-R** [comment]
Assign it to me please

**Comment by DevSwayam** [comment]
> Assign it to me please

Did. If you face any issue please let me know in discussion tab.

**Comment by karthickbharathi1** [comment]
Can you assign this issue to me?

**Comment by anshadanchu368** [comment]
please assign it to me

**Comment by DevSwayam** [comment]
> Can you assign this issue to me?

Sorry brother the issue has been fixed in or #76

**Comment by DevSwayam** [comment]
Thank you all for participating will post new issues for beginners to work on.
