### ISSUE TITLE
The HighLight Issue in NavBar

### ISSUE THREAD

**Issue by DevSwayam** [TechieeGeeeks/JobSet#74]
## Important Note:
Why i am making such simple issues? Cause i want ppl to learn how to contribute if you know Good Amount of stuff in frontend, Github please dont work on it.

### What is the Logic?
So when we click on any pages like (HOME, RESOURCES, FINDJOB) 
that component gets highlighted by blue color.

### How its done? 
There is an onclick function on each of them and it sets the index to particular page(0,1,2).
and in css property there is check for the index value if index is 0 then highlight this with blue color.

### What is Bug?
![image](https://github.com/TechieeGeeeks/JobSet/assets/99035115/b375139b-db9b-468a-bb85-9a804ed96dfa)
so Dashboarrd is not part of the pages on navbar. but when user navigates to the dashboard the last page from navbar still remains highlishted even though we are on dashboard

### What is Goal?
To stop highlighting that page which we not on right now.

### How to do it?
You can apply a onClick Function on the drop down items and when we navigate to drop down item you can setIndex to a particular value which is not being used.

**Comment by Xzm27** [comment]
The error can also occur at deeper links. I guess it will be better to aditionally check for parameters from the url to ensure the highlight is on the correct page. Let me know your take on that.

**Comment by DevSwayam** [comment]
> The error can also occur at deeper links. I guess it will be better to aditionally check for parameters from the url to ensure the highlight is on the correct page. Let me know your take on that.

So you want to do it with useParams Hook?

**Comment by Xzm27** [comment]
That could have been one approach but its fixed now check i pr. I used NavLink to check for active state.

**Comment by DevSwayam** [comment]
> That could have been one approach but its fixed now check i pr. I used NavLink to check for active state.

Ok looking at it
