### ISSUE TITLE
Reduce Gaps in Sections [Early Bird 🐣 Issue]

### ISSUE THREAD

**Issue by DevSwayam** [TechieeGeeeks/JobSet#84]
### There is alot of gaps in 2 two section i want to reduce it.

![image](https://github.com/TechieeGeeeks/JobSet/assets/99035115/c8ef1fb5-39e7-404d-bc6e-09c7289c4070)
 
![image](https://github.com/TechieeGeeeks/JobSet/assets/99035115/b3d15ddb-c9ec-4cd5-b86e-aaf1bcee7c22)

This task is for Early Birds. Can you look over the related PR to this issue @vwakesahu ?

**Comment by vwakesahu** [comment]
Ok on it..

**Comment by DevSwayam** [comment]
> Ok on it..

Dont do it. Some Newbie will work on this issue just review their changes. If noone does it we can change it at last.

**Comment by Pravin-P-Singh** [comment]
on it

**Comment by vwakesahu** [comment]
good work @Pravin-P-Singh
